### ISSUE TITLE
How to change hot key ?

### ISSUE THREAD

**Issue by hnomkeng** [TomGrobbe/Firing-Modes#1]
I need change hot key , hot key firing mode same hot key other script.

**Comment by TomGrobbe** [comment]
There's currently no way to change the keybindings unless you change the code and recompile it for yourself. In the future I'll try to add a config file to have some customization options.

**Comment by TomGrobbe** [comment]
@hnomkeng I've just added an option for this in the latest release. Checkout the README.md file for instructions.
